<html>
	<head>
		<title>Girish Constructions</title>
		<meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <meta name="keyword" content="Real Estate, Buy, Sell, Rent, Residency, Shops, homes, houses, Allahabad">
	    <meta name="description" content="Girish Constructions provides a single stop where you can sell, buy, rent your real estate property.">
	    <meta name="robots" content="">
		<link href="{$SITE_URL}foundation/css/bootstrap{if $SERVER.is_developer<>1}.min{/if}.css" rel="stylesheet" type="text/css"/>
		<!--<link async href="{$SITE_URL}foundation/css/chosen.min.css" rel="stylesheet" type="text/css"/>-->
		<link href="{$SITE_URL}style{if $SERVER.is_developer<>1}.min{/if}.css" rel="stylesheet" type="text/css"/>
		<script src="{$SITE_URL}foundation/js/jquery-1.10.2{if $SERVER.is_developer<>1}.min{/if}.js"></script>
		<link rel="icon" type="image/png"  href="{$SITE_URL}images/icons/home_icon50.png" />
		<!--<script async src="{$SITE_URL}foundation/js/jquery.lazyload.min.js"></script>-->
		<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Girish Constructions",
  "address" : {
    "@type" : "PostalAddress",
    "addressLocality" : "Allahabad"
  }
}
</script>
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Product",
  "name" : "Construction",
  "description" : "Buy your dream homes, office spaces and plots",
  "offers" : {
    "@type" : "Offer",
    "price" : "minimum possible price"
  },
  "aggregateRating" : {
    "@type" : "AggregateRating",
    "bestRating" : "best price"
  }
}
</script>
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Girish Constructions",
  "address" : {
    "@type" : "PostalAddress",
    "addressLocality" : "Allahabad"
  },
  "url" : "http://www.girishconstructions.com/",
  "review" : {
    "@type" : "Review",
    "author" : {
      "@type" : "Person",
      "name" : "Santosh - Allahabad"
    },
    "reviewRating" : {
      "@type" : "Rating",
      "bestRating" : "Simply, Great"
    }
  }
}
</script>
	</head>
	<body>
	{include file="error.tpl"}
	{include file="gi-header-top.tpl"}
	