<?php /* Smarty version Smarty-3.1.19, created on 2015-02-15 16:17:37
         compiled from "gi-header.tpl" */ ?>
<?php /*%%SmartyHeaderCode:3569714154bc95ff82f041-55344154%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '4fa6ad1debfd4f2cc343349b06f025948cfb8bec' => 
    array (
      0 => 'gi-header.tpl',
      1 => 1424017050,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '3569714154bc95ff82f041-55344154',
  'function' => 
  array (
  ),
  'version' => 'Smarty-3.1.19',
  'unifunc' => 'content_54bc95ff885c87_10795668',
  'variables' => 
  array (
    'SITE_URL' => 0,
    'SERVER' => 0,
  ),
  'has_nocache_code' => false,
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_54bc95ff885c87_10795668')) {function content_54bc95ff885c87_10795668($_smarty_tpl) {?><html>
	<head>
		<title>Girish Constructions</title>
		<meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <meta name="keyword" content="Real Estate, Buy, Sell, Rent, Residency, Shops, homes, houses, Allahabad">
	    <meta name="description" content="Girish Constructions provides a single stop where you can sell, buy, rent your real estate property.">
	    <meta name="robots" content="">
		<link href="<?php echo $_smarty_tpl->tpl_vars['SITE_URL']->value;?>
foundation/css/bootstrap<?php if ($_smarty_tpl->tpl_vars['SERVER']->value['is_developer']!=1) {?>.min<?php }?>.css" rel="stylesheet" type="text/css"/>
		<!--<link async href="<?php echo $_smarty_tpl->tpl_vars['SITE_URL']->value;?>
foundation/css/chosen.min.css" rel="stylesheet" type="text/css"/>-->
		<link href="<?php echo $_smarty_tpl->tpl_vars['SITE_URL']->value;?>
style<?php if ($_smarty_tpl->tpl_vars['SERVER']->value['is_developer']!=1) {?>.min<?php }?>.css" rel="stylesheet" type="text/css"/>
		<script src="<?php echo $_smarty_tpl->tpl_vars['SITE_URL']->value;?>
foundation/js/jquery-1.10.2<?php if ($_smarty_tpl->tpl_vars['SERVER']->value['is_developer']!=1) {?>.min<?php }?>.js"></script>
		<link rel="icon" type="image/png"  href="<?php echo $_smarty_tpl->tpl_vars['SITE_URL']->value;?>
images/icons/home_icon50.png" />
		<!--<script async src="<?php echo $_smarty_tpl->tpl_vars['SITE_URL']->value;?>
foundation/js/jquery.lazyload.min.js"></script>-->
		<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Girish Constructions",
  "address" : {
    "@type" : "PostalAddress",
    "addressLocality" : "Allahabad"
  }
}
</script>
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Product",
  "name" : "Construction",
  "description" : "Buy your dream homes, office spaces and plots",
  "offers" : {
    "@type" : "Offer",
    "price" : "minimum possible price"
  },
  "aggregateRating" : {
    "@type" : "AggregateRating",
    "bestRating" : "best price"
  }
}
</script>
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "LocalBusiness",
  "name" : "Girish Constructions",
  "address" : {
    "@type" : "PostalAddress",
    "addressLocality" : "Allahabad"
  },
  "url" : "http://www.girishconstructions.com/",
  "review" : {
    "@type" : "Review",
    "author" : {
      "@type" : "Person",
      "name" : "Santosh - Allahabad"
    },
    "reviewRating" : {
      "@type" : "Rating",
      "bestRating" : "Simply, Great"
    }
  }
}
</script>
	</head>
	<body>
	<?php echo $_smarty_tpl->getSubTemplate ("error.tpl", $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, 0, null, array(), 0);?>

	<?php echo $_smarty_tpl->getSubTemplate ("gi-header-top.tpl", $_smarty_tpl->cache_id, $_smarty_tpl->compile_id, 0, null, array(), 0);?>

	<?php }} ?>
